# Generated by Django 5.0.8 on 2025-03-20 07:57

import agents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agent_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agent_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('profile_image_path', models.ImageField(blank=True, null=True, upload_to=agents.models.upload_profile_image, validators=[django.core.validators.validate_image_file_extension])),
                ('is_active', models.BooleanField(default=False)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('license_document_path', models.ImageField(blank=True, null=True, upload_to=agents.models.upload_license_document, validators=[django.core.validators.validate_image_file_extension])),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected'), ('C', 'Cancelled')], default='P', max_length=100)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agent_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_applications', to='agents.agentaccount')),
            ],
        ),
    ]
