# Generated by Django 5.0.8 on 2025-03-08 07:16

import agents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agent_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agent_name', models.CharField(max_length=100)),
                ('profile_image_path', models.ImageField(blank=True, null=True, upload_to=agents.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_approved', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
