# Generated by Django 5.0.8 on 2025-04-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaccount',
            name='contact_number_1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentaccount',
            name='contact_number_2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
