test_listings = [{
    'title': 'test title 1',
    'description': 'test description 1',
    'listing_type': 'FS',
    'property_type': 'HL',
    'price': 1000000,
    'property_size': 100,
    'bedrooms': 2,
    'bathrooms': 2,
    'province': 'Province 1',
    'city': 'City 1',
            'baranggay': 'Baranggay 1',
            'street': 'Street 1'
}, {
    'title': 'test title 2',
    'description': 'test description 2',
    'listing_type': 'FS',
    'property_type': 'HL',
    'price': 1200000,
    'property_size': 120,
    'bedrooms': 2,
    'bathrooms': 2,
    'province': 'Province 1',
    'city': 'City 1',
            'baranggay': 'Baranggay 1',
            'street': 'Street 1'
}, {
    'title': 'test title 3',
    'description': 'test description 3',
    'listing_type': 'FS',
    'property_type': 'HL',
    'price': 2000000,
    'property_size': 180,
    'bedrooms': 3,
    'bathrooms': 2,
    'province': 'Province 1',
    'city': 'City 2',
            'baranggay': 'Baranggay 2',
            'street': 'Street 2'
}, {
    'title': 'test title 4',
    'description': 'test description 4',
    'listing_type': 'FR',
    'property_type': 'HL',
    'price': 4000,
    'property_size': 28,
    'bedrooms': 1,
    'bathrooms': 1,
    'province': 'Province 1',
    'city': 'City 1',
            'baranggay': 'Baranggay 1',
            'street': 'Street 1'
}, {
    'title': 'test title 5',
    'description': 'test description 5',
    'listing_type': 'FR',
    'property_type': 'HL',
    'price': 5000,
    'property_size': 30,
    'bedrooms': 1,
    'bathrooms': 1,
    'province': 'Province 2',
    'city': 'City 3',
            'baranggay': 'Baranggay 1',
            'street': 'Street 4'
}, {
    'title': 'test title 6',
    'description': 'test description 6',
    'listing_type': 'FS',
    'property_type': 'RL',
    'price': 100000,
    'property_size': 100,
    'province': 'Province 2',
    'city': 'City 1',
            'baranggay': 'Baranggay 1',
            'street': 'Street 1'
}, {
    'title': 'test title 7',
    'description': 'test description 7',
    'listing_type': 'FS',
    'property_type': 'CL',
    'price': 200000,
    'property_size': 120,
    'province': 'Province 1',
    'city': 'City 1',
            'baranggay': 'Baranggay 1',
            'street': 'Street 1'
}, {
    'title': 'test title 8',
    'description': 'test description 8',
    'listing_type': 'FS',
    'property_type': 'RL',
    'price': 80000,
    'property_size': 80,
    'province': 'Province 2',
    'city': 'City 2',
            'baranggay': 'Baranggay 3',
            'street': 'Street 1'
}, {
    'title': 'test title 9',
    'description': 'test description 9',
    'listing_type': 'FS',
    'property_type': 'HL',
    'price': 1400000,
    'property_size': 120,
    'bedrooms': 2,
    'bathrooms': 2,
    'province': 'Province 1',
    'city': 'City 2',
            'baranggay': 'Baranggay 1',
            'street': 'Street 1'
}, {
    'title': 'test title 10',
    'description': 'test description 10',
    'listing_type': 'FR',
    'property_type': 'CL',
    'price': 30000,
    'property_size': 100,
    'province': 'Province 2',
    'city': 'City 2',
            'baranggay': 'Baranggay 1',
            'street': 'Street 2'
}, {
    'title': 'test title 11',
    'description': 'test description 11',
    'listing_type': 'FC',
    'property_type': 'HL',
    'price': 1000000,
    'property_size': 100,
    'bedrooms': 2,
    'bathrooms': 1,
    'province': 'Province 3',
    'city': 'City 4',
            'baranggay': 'Baranggay 7',
            'street': 'Street 5'
}, {
    'title': 'test title 12',
    'description': 'test description 12',
    'listing_type': 'FC',
    'property_type': 'RL',
    'price': 1000000,
    'property_size': 100,
    'province': 'Province 2',
    'city': 'City 3',
            'baranggay': 'Baranggay 3',
            'street': 'Street 3'
}, {
    'title': 'test title 12',
    'description': 'test description 12',
    'listing_type': 'FR',
    'property_type': 'CO',
    'price': 20000,
    'property_size': 80,
    'bedrooms': 2,
    'bathrooms': 1,
    'province': 'Province 1',
    'city': 'City 1',
            'baranggay': 'Baranggay 1',
            'street': 'Street 1'
}, {
    'title': 'test title 13',
    'description': 'test description 13',
    'listing_type': 'FR',
    'property_type': 'CO',
    'price': 18000,
    'property_size': 80,
    'bedrooms': 2,
    'bathrooms': 1,
    'province': 'Province 2',
    'city': 'City 2',
            'baranggay': 'Baranggay 1',
            'street': 'Street 1'
}, {
    'title': 'test title 14',
    'description': 'test description 14',
    'listing_type': 'FS',
    'property_type': 'CO',
    'price': 3000000,
    'property_size': 100,
    'bedrooms': 2,
    'bathrooms': 2,
    'province': 'Province 1',
    'city': 'City 1',
            'baranggay': 'Baranggay 1',
            'street': 'Street 1'
}, {
    'title': 'test title 15',
    'description': 'test description 15',
    'listing_type': 'FR',
    'property_type': 'CO',
    'price': 2400000,
    'property_size': 88,
    'bedrooms': 1,
    'bathrooms': 1,
    'province': 'Province 2',
    'city': 'City 2',
            'baranggay': 'Baranggay 1',
            'street': 'Street 1'
}, {
    'title': 'test title 16',
    'description': 'test description 16',
    'listing_type': 'FS',
    'property_type': 'HL',
    'price': 8000000,
    'property_size': 300,
    'bedrooms': 3,
    'bathrooms': 2,
    'province': 'Province 3',
    'city': 'City 3',
            'baranggay': 'Baranggay 2',
            'street': 'Street 1'
}, {
    'title': 'test title 17',
    'description': 'test description 17',
    'listing_type': 'FS',
    'property_type': 'RL',
    'price': 50000,
    'property_size': 60,
    'province': 'Province 2',
    'city': 'City 2',
            'baranggay': 'Baranggay 1',
            'street': 'Street 2'
}, {
    'title': 'test title 1',
    'description': 'test description 18',
    'listing_type': 'FR',
    'property_type': 'CL',
    'price': 80000,
    'property_size': 800,
    'province': 'Province 1',
    'city': 'City 2',
            'baranggay': 'Baranggay 3',
            'street': 'Street 3'
}, {
    'title': 'test title 1',
    'description': 'test description 19',
    'listing_type': 'FR',
    'property_type': 'CL',
    'price': 40000,
    'property_size': 500,
    'province': 'Province 3',
    'city': 'City 4',
            'baranggay': 'Baranggay 4',
            'street': 'Street 5'
}, {
    'title': 'test title 20',
    'description': 'test description 20',
    'listing_type': 'FC',
    'property_type': 'HL',
    'price': 1000000,
    'property_size': 100,
    'bedrooms': 2,
    'bathrooms': 1,
    'province': 'Province 4',
    'city': 'City 3',
            'baranggay': 'Baranggay 2',
            'street': 'Street 1'
}]
