# Generated by Django 5.0.8 on 2025-03-20 07:57

import buyers.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='buyer_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image_path', models.ImageField(blank=True, null=True, upload_to=buyers.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('bio', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('buyer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='buyers.buyeraccount')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
    ]
