# Generated by Django 5.0.8 on 2025-02-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeraccount',
            name='favorite_listings',
            field=models.ManyToManyField(to='listings.listing'),
        ),
    ]
