# Generated by Django 5.0.8 on 2025-03-16 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
        ('listings', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyeraccount',
            name='wishlist',
        ),
        migrations.CreateModel(
            name='WishlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('buyer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='buyers.buyeraccount')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
    ]
