# Generated by Django 5.0.8 on 2024-09-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyeraccount',
            old_name='listing_favorites',
            new_name='favorite_listings',
        ),
    ]
