# Generated by Django 5.0.8 on 2025-02-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeraccount',
            name='contact_number_1',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyeraccount',
            name='contact_number_2',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
