# Generated by Django 5.0.8 on 2025-03-20 07:57

import django.core.validators
import django.db.models.deletion
import sellers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=500)),
                ('contact_number_1', models.BigIntegerField(blank=True, null=True)),
                ('contact_number_2', models.BigIntegerField(blank=True, null=True)),
                ('profile_image_path', models.ImageField(blank=True, null=True, upload_to=sellers.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected'), ('C', 'Cancelled')], default='P', max_length=100)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_applications', to='sellers.selleraccount')),
            ],
        ),
    ]
