# Generated by Django 5.0.8 on 2024-11-10 12:46

import django.core.validators
import django.db.models.deletion
import sellers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=500)),
                ('birthdate', models.DateField(blank=True, editable=False, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], editable=False, max_length=20, null=True)),
                ('contact_number_1', models.PositiveIntegerField()),
                ('contact_number_2', models.PositiveIntegerField(blank=True, null=True)),
                ('seller_image_url', models.ImageField(blank=True, editable=False, null=True, upload_to=sellers.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('valid_id_url', models.ImageField(blank=True, editable=False, null=True, upload_to=sellers.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('status', models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default=('P', 'Pending'), max_length=10)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerEmailValidationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField(error_messages={'error': 'Invalid PIN'}, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=500)),
                ('birthdate', models.DateField(blank=True, editable=False, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], editable=False, max_length=20, null=True)),
                ('contact_number_1', models.PositiveIntegerField()),
                ('contact_number_2', models.PositiveIntegerField(blank=True, null=True)),
                ('seller_image_url', models.ImageField(blank=True, editable=False, null=True, upload_to=sellers.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('valid_id_url', models.ImageField(blank=True, editable=False, null=True, upload_to=sellers.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('sellerapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sellers.sellerapplication')),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('sellers.sellerapplication',),
        ),
    ]
