# Generated by Django 5.0.8 on 2024-09-18 18:54

import django.core.validators
import django.db.models.deletion
import sellers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=500)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('contact_number_1', models.PositiveIntegerField()),
                ('contact_number_2', models.PositiveIntegerField(blank=True, null=True)),
                ('seller_image_url', models.ImageField(upload_to=sellers.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('valid_id_url', models.ImageField(upload_to=sellers.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
