# Generated by Django 5.0.8 on 2025-03-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplication',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected'), ('C', 'Cancelled')], default='P', max_length=100),
        ),
    ]
