# Generated by Django 5.0.8 on 2024-10-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
