# Generated by Django 5.0.8 on 2025-02-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplication',
            name='contact_number_1',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='contact_number_2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selleremailvalidationrequest',
            name='contact_number_1',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='selleremailvalidationrequest',
            name='contact_number_2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
