# Generated by Django 5.0.8 on 2025-02-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_sellerapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccount',
            name='business_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='business_address',
            field=models.CharField(max_length=500),
        ),
    ]
