# Generated by Django 5.0.8 on 2025-03-31 04:01

import django.core.validators
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('HL', 'House and Lot'), ('CL', 'Commercial Lot'), ('RL', 'Residentail Lot'), ('CO', 'Condominium')], max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('lot_area', models.PositiveIntegerField(blank=True, null=True)),
                ('floor_area', models.PositiveIntegerField(blank=True, null=True)),
                ('num_of_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image1_path', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('image2_path', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('image3_path', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('image4_path', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('image5_path', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_to, validators=[django.core.validators.validate_image_file_extension])),
                ('status', models.CharField(choices=[('R', 'Ready for Listing'), ('L', 'Listed'), ('H', 'On Hold'), ('S', 'Sold')], default='R', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
