# Generated by Django 5.0.8 on 2025-03-07 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='seller_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.selleraccount'),
        ),
    ]
