# Generated by Django 5.0.8 on 2025-03-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('R', 'Ready for Listing'), ('L', 'Listed'), ('OA', 'Offer Accepted'), ('S', 'Sold')], default='R', max_length=100),
        ),
    ]
