# Generated by Django 5.0.8 on 2025-03-07 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_is_deleted'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='seller_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='sellers.selleraccount'),
        ),
    ]
