# Generated by Django 5.0.8 on 2025-03-18 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_alter_agentapplication_status'),
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_properties', to='agents.agentaccount')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agents', to='properties.property')),
            ],
        ),
    ]
