# Generated by Django 5.0.8 on 2025-03-20 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('properties', '0001_initial'),
        ('property_agent_assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyagentassignment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_properties', to='agents.agentaccount'),
        ),
        migrations.AddField(
            model_name='propertyagentassignment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agents', to='properties.property'),
        ),
    ]
