# Generated by Django 5.0.8 on 2024-08-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
