# Generated by Django 5.0.8 on 2024-08-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='PasswordReset',
            new_name='RequestPasswordReset',
        ),
    ]
