# Generated by Django 5.0.8 on 2024-08-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_requestemailverification_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestEmailVerification',
            new_name='EmailVerificationRequest',
        ),
        migrations.RenameModel(
            old_name='RequestPasswordReset',
            new_name='PasswordResetRequest',
        ),
    ]
