# Generated by Django 5.0.8 on 2024-08-15 05:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_requestemailverification_emailverificationrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationrequest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 8, 15, 13, 28, 34, 467776)),
        ),
        migrations.AlterField(
            model_name='emailverificationrequest',
            name='pin',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buyer', models.BooleanField(default=True)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
