# Generated by Django 5.0.8 on 2024-08-15 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userroles_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRoles',
            new_name='Roles',
        ),
    ]
