# Generated by Django 5.0.8 on 2024-08-25 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_roles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationrequest',
            name='pin',
            field=models.IntegerField(error_messages={'error': 'Invalid PIN'}, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
