# Generated by Django 5.0.8 on 2024-09-17 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_created_at_alter_listing_image'),
        ('user', '0013_alter_roles_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('contact_number_1', models.PositiveIntegerField(
                    blank=True, null=True)),
                ('contact_number_2', models.PositiveIntegerField(
                    blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('listing_favorites', models.ManyToManyField(to='listings.listing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
