# Generated by Django 5.0.8 on 2024-09-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_profile_buyerprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyerProfile',
        ),
    ]
