# Generated by Django 5.0.8 on 2025-03-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('BT', 'Bank Transfer'), ('BL', 'Bank Loan'), ('I', 'Installment'), ('CP', 'Cash Payment'), ('CHP', 'Check Payment')], default='BT', max_length=50)),
                ('status', models.CharField(choices=[('W', 'Waiting for approval'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Cancelled')], default='W', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('buyer_offer_response', models.CharField(choices=[('P', 'Pending'), ('A', 'Accept'), ('R', 'Reject'), ('C', 'Cancel')], default='P', max_length=50)),
                ('seller_offer_response', models.CharField(choices=[('P', 'Pending'), ('A', 'Accept'), ('R', 'Reject'), ('C', 'Cancel')], default='P', max_length=50)),
                ('agent_offer_response', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Accept'), ('R', 'Reject'), ('C', 'Cancel')], default='P', max_length=50, null=True)),
            ],
        ),
    ]
