# Generated by Django 5.0.8 on 2025-03-31 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('buyers', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('listings', '0002_initial'),
        ('offers', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='agent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='agents.agentaccount'),
        ),
        migrations.AddField(
            model_name='offer',
            name='buyer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='buyers.buyeraccount'),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='offer',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='offer',
            name='seller_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='sellers.selleraccount'),
        ),
    ]
