# Generated by Django 5.0.8 on 2024-09-22 02:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('listing_type', models.CharField(choices=[('FS', 'For Sale'), ('FR', 'For Rent'), ('FC', 'Foreclosure')], max_length=20)),
                ('property_type', models.CharField(choices=[('HL', 'House and Lot'), ('CL', 'Commercial Lot'), ('RL', 'Residential Lot'), ('CO', 'Condominium')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/listings', validators=[django.core.validators.validate_image_file_extension])),
                ('property_size', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('baranggay', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.selleraccount')),
            ],
        ),
    ]
