# Generated by Django 5.0.8 on 2025-03-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('FS', 'For Sale'), ('FR', 'For Rent'), ('FC', 'Foreclosure')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('H', 'On Hold'), ('S', 'Sold'), ('C', 'Cancelled'), ('R', 'Removed')], default='A', max_length=100)),
            ],
        ),
    ]
