# Generated by Django 5.0.8 on 2024-10-21 15:51

import django.core.validators
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.upload_to, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
