# Generated by Django 5.0.8 on 2024-08-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='default_house_for_sale.jpg', upload_to='images/listings'),
        ),
    ]
