# Generated by Django 5.0.8 on 2025-04-07 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('IP', 'In Process'), ('CO', 'Completed'), ('CA', 'Cancelled')], default='P', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='offers.offer')),
            ],
        ),
    ]
