# Generated by Django 5.0.8 on 2025-02-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verification_token',
            new_name='email_verification_pin',
        ),
    ]
